import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/general.scss';
import '../styles/helpers.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Note POC App',
  description: 'Generated by Lala Hakobyan',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light-theme">
      <head>
        <title>My Notes</title>
        <link rel="manifest" href="/manifest.json" />
        {/* Load script in a blocking way (simulate performance leak) */}
        {/*<Script src="/assets/icons/heavy-analytics-script.js" strategy="beforeInteractive" />*/}
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        { <script src="/assets/js/heavy-analytics-script.js" /> }

        <script type="speculationrules"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              prerender: [
                {
                  where: { selector_matches: '.prerender' },
                  eagerness: 'immediate' // "immediate" for page load or "moderate" (on hover)
                },
                {
                  where: { selector_matches: '.prerender-hover' },
                  eagerness: 'moderate' // "immediate" for page load or "moderate" (on hover)
                }
              ],
              prefetch: [{
                where: { selector_matches: '.prefetch' },
                eagerness: 'immediate'
              }]
            }),
          }}
        />

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
